config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile', to: 'users#show'
  get 'adverts', to: 'home#index'
  get 'search', to: 'adverts#search_index', as: 'search'

  resources :users, only: [:show, :create] do
    resources :adverts, except: [:index]
    post 'adverts/:id/make_archive', to: 'adverts#make_archived', as: 'advert_archive'
    post 'adverts/:id/make_moderated', to: 'adverts#make_moderated', as: 'advert_moderate'
    get 'adverts/:id/history', to: 'adverts#history', as: 'advert_history'
  end


  namespace :admin do
    resources :users, only: [:show]
    resources :adverts
    resources :categories, only: [:create, :destroy, :update]
    get '', to: 'adverts#index'
  end
  
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :avatar
  enum role: [:user, :admin]

  has_many :adverts
  has_many :identities, dependent: :destroy

  mount_uploader :avatar, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook, :twitter, :vkontakte]

  def role?(checked_role)
    checked_role == role
  end

  def self.find_for_oauth(auth)
    identity = Identity.find_for_oauth(auth)
    user = identity.user
    image = auth.info.image

    if user.nil?
      email = auth.info.email
      user = User.find_by_email(email) if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
        email: email,
        password: Devise.friendly_token[0,20],
        remote_avatar_url: image.to_s)
        user.save!
      end
    end

    if image.present?
      user.update_attribute(:remote_avatar_url, image)
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:show]

    def show
      @adverts = @user.adverts.admin_available.page params[:page]
      authorize [:admin, User]
    end

    private

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(request.env["omniauth.auth"])
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :vkontakte].each do |provider|
    provides_callback_for provider
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:create]
  
  def show
    @user = current_user
    authorize @user || User
    category = params[:filter].try(:fetch, :category)
    status = params[:filter].try(:fetch, :ad_type)
    @q = @user.adverts.search(category_id_eq: category, ad_type_eq: status)
    @q.sorts = 'created_at asc'
    @adverts = @q.result().page params[:page]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.new(user_params)
    @user.avatar = params[:avatar]
    @user.save
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :avatar
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    image_tag(user.avatar_url(:standard), class: 'avatar brd')
  end
end

app/views/users/index.html.slim
- @users.each do |user|
  = user.email
  = link_to "Profile", user_path(user)
  br/

app/views/users/show.html.slim
.user-profile
  .user-avatar
    = user_avatar @user
  .profile-info
    | Email: 
    = @user.email
    br
    = link_to "New advert", new_user_advert_path(@user)

.filter-block#user-show-block
  a.search-filter-link
    | Parameters
    span.caret
    .search-filter-form
      = search_form_for @q, url: current_user, method: :get, remote: true, class: 'navbar-form navbar-left' do |f|
        = f.select :category_id_eq, options_from_collection_for_select(Category.all, :id, :name, @q.category_id_eq), {include_blank: 'Select category... '}
        br
        = f.select :ad_type_eq, options_from_collection_for_select(Advert.ad_types, 'second', 'first', @q.ad_type_eq), {include_blank: 'Select type... '}
  .tag-container
    a#category-tag
      | Category
    a#ad_type-tag
      | Status

br
.container.my-container
  ul.list-group#user-adverts-list
    = render @adverts

#pagination-nav
  - if @adverts.present?
    = paginate @adverts, remote: true, params: {controller: 'users', action: 'show'}

app/views/users/show.js.erb
$('#pagination-nav').html('<%= j paginate @adverts, remote: true, params: {controller: 'users', action: 'show'} %>');
$('#user-adverts-list').html('<%= j render @adverts %>');
setStatuses();