config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile', to: 'users#show'
  get 'adverts', to: 'home#index'
  get 'search', to: 'adverts#search_index', as: 'search'

  resources :users, only: [:show, :create] do
    resources :adverts, except: [:index]
    post 'adverts/:id/make_archive', to: 'adverts#make_archived', as: 'advert_archive'
    post 'adverts/:id/make_moderated', to: 'adverts#make_moderated', as: 'advert_moderate'
    get 'adverts/:id/history', to: 'adverts#history', as: 'advert_history'
  end


  namespace :admin do
    resources :users, only: [:show]
    resources :adverts
    resources :categories, only: [:create, :destroy, :update]
    get '', to: 'adverts#index'
  end
  
  root 'home#index'
end

app/models/advert.rb
class Advert < ApplicationRecord
  paginates_per 10

  include AASM
  has_paper_trail
  enum status: [:recent, :moderated, :canceled, :published, :archived]
  enum ad_type: [:Sale, :Buy, :Exchange, :Service, :Rent]

  validates :price, numericality: { greater_than: 0 }
  validates :title, presence: true, length: { maximum: 20 }
  validates :category_id, presence: true
  validates :ad_type, presence: true

  scope :published, -> { where(status: :published) }
  scope :moderated, -> { where(status: :moderated) }
  scope :admin_available, -> { where status: [:moderated, :published, :canceled] }

  belongs_to :user
  belongs_to :category

  has_many :logs, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  aasm column: :status, enum: true do
    state :recent, initial: true
    state :moderated
    state :canceled
    state :published
    state :archived

    event :archive do
      transitions to: :archived, from: [:recent, :moderated, :published, :canceled]
    end

    event :publish do
      transitions to: :published, from: :moderated
    end

    event :cancel do
      transitions to: :canceled, from: :moderated
    end

    event :refresh do
      transitions to: :recent
    end

    event :moderate do
      transitions to: :moderated, from: [:recent, :archived]
    end
  end

  def self.set_archive
    yesterday = Time.zone.now.ago(1.day)
    @adverts = Advert.all.select { |ad| ad.published? }
    @adverts.each do |advert|
      if advert.logs.last.time < yesterday
        advert.archive!
        advert.create_log(advert.user, 'Auto set after 1 day in publihed.')
        puts "#{Time.now} | #{advert.title} - Success!"
      end
    end
    puts "#{Time.now} | Done!"
  end

  def create_log(modifier, comment = nil)
    time = DateTime.now
    prev_status = self.paper_trail.previous_version.try(:status) || 'recent'
    new_status = self.status
    if prev_status != new_status
      self.logs.create(user_id: modifier.id, time: time, prev_status: prev_status, new_status: new_status, comment: comment)
    end
  end

  def owner?(user)
    user == self.user
  end
end

app/controllers/admin/adverts_controller.rb
module Admin
  class AdvertsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_advert, only: [:show, :update]

    def index
      @categories = Category.all
      @category = Category.new
      @adverts = Advert.moderated
      @users = User.all
      authorize [:admin, Advert]
    end

    def show
    end

    def update
      @advert.update(advert_params)
      comment = params[:log].try(:fetch, :comment)
      @advert.create_log(current_user, comment)
    end

    private

    def set_advert
      @advert = Advert.find(params[:id])
    end

    def advert_params
      params.require(:advert).permit(
        :title,
        :description,
        :price,
        :status,
        :category,
        image_attributes: [:id, :body, :advert_id]
      )
    end
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :authenticate_user!, except: [:search_index, :show]
  before_action :set_user, except: [:search_index, :filter]
  before_action :set_advert, except: [:show, :new, :create, :search_index]

  def show
    user = User.find(params[:user_id])
    @advert = user.adverts.select { |ad| ad.id == params[:id].to_i }.first
    if @advert.nil?
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  end

  def new
    @advert = @user.adverts.build
    authorize @advert
  end

  def edit
    authorize @advert
  end

  def create
    @advert = @user.adverts.new(advert_params)
    if @advert.save
      create_images
      redirect_to @user, notice: 'Advert was succesfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @advert.update(advert_params)
      @advert.refresh!
      @advert.create_log(@advert.user)
      redirect_to [@user, @advert]
    else
      render action: 'edit'
    end
  end

  def search_index
    @search_phrase = params[:q][:title_or_description_cont]
    @q = Advert.published.ransack(params[:q])
    @q.sorts = 'price desc' if @q.sorts.empty?
    @adverts = @q.result(distinct: true).page params[:page]
    render 'search_index'
  end

  def make_archived
    @advert.archive!
    @advert.create_log(@advert.user)
    respond_to do |format|
      format.js {}
    end
  end

  def make_moderated
    @advert.moderate!
    @advert.create_log(@advert.user)
    respond_to do |format|
      format.js {}
    end
  end

  def history
    @logs = @advert.logs
  end

  private

  def set_advert
    @advert = Advert.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def create_images
    return if params[:images].nil?
    params[:images]['body'].each do |a|
      @advert.images.create!(body: a)
    end
  end

  def advert_params
    params.require(:advert).permit(
      :title,
      :description,
      :price,
      :ad_type,
      :category_id,
      image_attributes: [:id, :body, :advert_id]
    )
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
  def advert_avatar(advert)
    if advert.images.present?
      image_tag(advert.images.first.body_url(:standard), class: 'avatar brd')
    else
      image_tag('photo_icon', version: :standart, class: 'brd', size: '300x300')
    end
  end
end

app/views/admin/adverts/_advert.html.slim
.panel.panel-default
  .panel-body
    .panel-more1.inline-element
      = advert_avatar advert
    .panel-info
      strong 
        = advert.title
      p
        = advert.price
        br/
        = advert.category.name
      p
        h3
          = advert.status

    .button-group role='group' 
      button.btn.btn-success#accept-button type='button' data-text='accept' 
        | Accept
      button.btn.btn-danger#reject-button type='button' data-text='reject'
        | Reject
      .comment-container data-comment-container-id='#{advert.id}'
        = text_area(:log, :comment, cols: 40, rows: 4, class: 'comment-field', placeholder: 'Write comment...')
        button#comment_send type='button' disabled="disabled"
          | Send
      input#control-hidden-status type='hidden' data-id="#{advert.id}" data-controller='#{admin_advert_path(advert)}'
    .button-container
      = button_to 'History',  user_advert_history_path(advert.user, advert), method: :get, form_class: 'history-form'
      = button_to 'Show', admin_advert_path(advert), method: :get, form_class: 'show-form'

app/views/admin/adverts/index.html.slim
.row
  .col-md-2.category-area
    ul.vertical#categories
      - @categories.each do |category|
        = render partial: 'admin/categories/category', object: category
    a.glyphicon.glyphicon-plus#new-category-button aria-hidden="true"
    #new-category-form
      = render partial: 'admin/categories/form', object: @category, locals: {category: @category}
  .col-md-10
    .button-group.switch-buttons role='group' 
      a.btn.btn-primary.btn-lg.outline.button-active#switch-to-adverts-button
        | Adverts
      a.btn.btn-primary.btn-lg.outline#switch-to-users-button
        | Users

    .container.my-container#admin-adverts-list
      ul.list-group
        - @adverts.each do |advert|
          li
            = render advert

    .container.my-container#admin-users-list
      ul.list-group
        - @users.each do |user|
          li
            = render user

app/views/admin/adverts/show.html.slim
= advert_avatar(@advert)
h1.inline-element.title = @advert.title
h3 = @advert.description
h3 = @advert.status
.image-container
  - @advert.images.each do |image|
    .img.brd
      a href="#{image.body_url}"
        = image_tag(image.body_url(:standard))