config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile', to: 'users#show'
  get 'adverts', to: 'home#index'
  get 'search', to: 'adverts#search_index', as: 'search'

  resources :users, only: [:show, :create] do
    resources :adverts, except: [:index]
    post 'adverts/:id/make_archive', to: 'adverts#make_archived', as: 'advert_archive'
    post 'adverts/:id/make_moderated', to: 'adverts#make_moderated', as: 'advert_moderate'
    get 'adverts/:id/history', to: 'adverts#history', as: 'advert_history'
  end


  namespace :admin do
    resources :users, only: [:show]
    resources :adverts
    resources :categories, only: [:create, :destroy, :update]
    get '', to: 'adverts#index'
  end
  
  root 'home#index'
end

app/views/layouts/_authentication.html.slim
ul.auth-container
  li
    = link_to image_tag('twitter', size: '60x60'), user_twitter_omniauth_authorize_path
  li
    = link_to image_tag('facebook', size: '60x60'), user_facebook_omniauth_authorize_path
  li
    = link_to image_tag('vkontakte', size: '60x60'), user_vkontakte_omniauth_authorize_path

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      a.navbar-brand href="#{root_path}"  Adverts
    ul.nav.navbar-nav.navbar-right
      li.nav-li.search-form
        = search_form_for @q, url: search_path, method: :get, class: 'navbar-form navbar-left' do |f|
          = f.search_field :title_or_description_cont, class: 'form-control', placeholder: 'Search'
          = f.button '', type: :submit, class: 'search-submit-button glyphicon glyphicon-search'
      - if user_signed_in?
        li.dropdown
          a.dropdown-toggle data-toggle='dropdown' href='#'
            = current_user.email
            span.caret
          ul.dropdown-menu
            li
              = link_to 'Profile', profile_path
            li.divider
            li 
              = link_to 'Edit', edit_user_registration_path
            - if policy(User).admin_index?
              li
                = link_to 'Admin', admin_path
            li
              = link_to 'Log Out', destroy_user_session_path, :method => :delete
      - else
        li.nav-li
          = link_to 'Log In', new_user_session_path
        li.nav-li
          = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>AdService</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'dataturbolinkstrack': 'reload' %>
      <%= javascript_include_tag 'application', 'dataturbolinkstrack': 'reload' %>
    </head>

    <body>
      <%= render '/layouts/navbar' %>
      <% if !user_signed_in? %>
        <%= render '/layouts/authentication' %>
      <% end %>
      <%= yield %>
    </body>
  </html>